version: '3.8'

services:
  santander-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/sdw2023
      - DATABASE_USERNAME=sdw2023
      - DATABASE_PASSWORD=sdw2023
    depends_on:
      - postgres
    networks:
      - sdw-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sdw2023
      POSTGRES_USER: sdw2023
      POSTGRES_PASSWORD: sdw2023
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sdw-network

volumes:
  postgres_data:

networks:
  sdw-network:
    driver: bridge
